# Generated by Django 4.2 on 2025-03-07 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('email_hash', models.CharField(max_length=64)),
                ('original_pdf', models.FileField(upload_to='uploads/')),
                ('anonymized_pdf', models.FileField(blank=True, null=True, upload_to='anonymized/')),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='final/')),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('review', models.TextField(blank=True, null=True)),
                ('reviewer_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.submission')),
            ],
        ),
    ]
