# Generated by Django 5.1.7 on 2025-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subtopics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='papers.domain'),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interests', models.ManyToManyField(related_name='reviewers', to='papers.domain')),
            ],
        ),
    ]
