# Generated by Django 5.1.7 on 2025-03-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_domain_submission_keywords_submission_domains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='keywords',
        ),
        migrations.AddField(
            model_name='submission',
            name='anonymize_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='anonymize_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='anonymize_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='revised_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
