# Generated by Django 5.1.7 on 2025-03-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_remove_submission_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='anonymize_contact',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='anonymize_org',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='anonymize_person',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
