# Generated by Django 5.1.7 on 2025-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_remove_submission_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='encrypted_filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
