# Generated by Django 5.1.7 on 2025-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_submission_encrypted_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Revize', 'Revize'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Hakeme Atandı', 'Hakeme Atandı'), ('Değerlendirildi', 'Değerlendirildi'), ('Final', 'Final')], default='Gönderildi', max_length=50),
        ),
    ]
