# Generated by Django 5.1.7 on 2025-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_domain_submission_keywords_submission_domains_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='keywords',
            new_name='extracted_keywords',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Hakeme Atandı', 'Hakeme Atandı'), ('Değerlendirildi', 'Değerlendirildi'), ('Revize Gerekli', 'Revize Gerekli'), ('Revize', 'Revize'), ('Final', 'Final')], default='Gönderildi', max_length=50),
        ),
    ]
