# Generated by Django 5.1.7 on 2025-03-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_rename_keywords_submission_extracted_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='domain',
            name='subtopics',
            field=models.TextField(default='Genel'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Revize Gerekli', 'Revize Gerekli'), ('Revize', 'Revize'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Hakeme Atandı', 'Hakeme Atandı'), ('Değerlendirildi', 'Değerlendirildi'), ('Final', 'Final')], default='Gönderildi', max_length=50),
        ),
    ]
