# Generated by Django 5.1.7 on 2025-03-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_alter_domain_name_alter_domain_subtopics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reviewer_assigned',
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.reviewer'),
        ),
    ]
