# Generated by Django 5.1.7 on 2025-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_remove_submission_reviewer_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='anonymized_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
