# Generated by Django 5.1.7 on 2025-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_submission_anonymized_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='restored',
            field=models.BooleanField(default=False),
        ),
    ]
