# Generated by Django 5.1.7 on 2025-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_submission_restored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='subtopics',
            field=models.TextField(default=''),
        ),
    ]
