# Generated by Django 5.1.7 on 2025-03-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_reviewer_subtopics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='subtopics',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='subtopics',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='domains',
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='papers.domain')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='papers.subtopic'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='interests',
            field=models.ManyToManyField(related_name='reviewers', to='papers.subtopic'),
        ),
    ]
