# Generated by Django 5.1.7 on 2025-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0016_remove_domain_subtopics_remove_reviewer_subtopics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='papers.subtopic'),
        ),
    ]
