# Generated by Django 5.1.7 on 2025-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_submission_reviewed_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
