# Generated by Django 5.1.7 on 2025-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0019_submission_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='author_email',
            new_name='email',
        ),
    ]
