# Generated by Django 5.1.7 on 2025-03-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0020_rename_author_email_submission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
    ]
